### ISSUE TITLE
Flag `kphp2cpp-binary` does not properly handle paths with `~`

### ISSUE THREAD

**Issue by i582** [VKCOM/ktest#5]
## Command

```shell
ktest bench --kphp2cpp-binary=~/kphp/objs/bin/kphp2cpp Benchmark.php
```

## Actual behavior

```
build error: fork/exec ~/kphp/objs/bin/kphp2cpp: no such file or directory
```

## Expected behavior

No error as for:

```shell
ktest bench --kphp2cpp-binary=/home/pmakhnev/kphp/objs/bin/kphp2cpp Benchmark.php
```

**Comment by quasilyte** [comment]
`~` is expanded by the means of bash or by another shell mechanism.
Bash doesn't expand `~` in some contexts, but it does expand it in this one:
```
ktest --kphp2cpp-binary ~/path
```
Notice the use of space instead of `=`.
You can also use variables if you prefer `=`.
```
ktest --kphp2cpp-binary=$HOME/path
```
So it's not a bug.

**Comment by quasilyte** [comment]
I would also suggest setting KPHP_ROOT env var instead of passing `--kphp2cpp-binary` directly.
